import { Employee } from "./types";

export const allEmployees: Employee[] = [
  {
    id: "AMD-001",
    name: "Abhoy Latif",
    position: "Sr frontend engineer",
    department: "IT",
    email: "ripu@meje.org",
    phoneNumber: "+447012345679s",
    employmentType: "full time",
    image: "",
  },
  {
    id: "AMD-002",
    name: "Dushane Daniel",
    position: "Head of finance",
    department: "Accounting",
    email: "daniel@meje.org",
    phoneNumber: "+4470123456795",
    employmentType: "full time",
    image: "",
  },
  {
    id: "AMD-003",
    name: "John doe",
    position: "Ux designer",
    department: "IT",
    email: "ripu1@meje.org",
    phoneNumber: "+4470123456791",
    employmentType: "intern",
    image: "",
  },
  {
    id: "AMD-004",
    name: "Riley Cooper",
    position: "Customer success Manager",
    department: "Customer success",
    email: "ripu2@meje.org",
    phoneNumber: "+4470123456790",
    employmentType: "contract",
    image: "",
  },
  {
    id: "AMD-005",
    name: "Abhoy Latif",
    position: "Sr frontend engineer",
    department: "IT",
    email: "ripu3@meje.org",
    phoneNumber: "+4470123456797",
    employmentType: "full time",
    image: "",
  },
];
